version: '1.0'
services:
  db:
    container_name: SecurityDB
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asd
    ports:
      - 5306:3306
    volumes:
      - "./forrasok/DB/docker_schema_script.sql:/docker-entrypoint-initdb.d/1.sql"

  api:
    container_name: SecurityApi
    image: axelnemes/securityapi:latest
    ports:
      - 5080:80
      - 5443:443