version: '1.0'
services:
  db:
    container_name: SecurityDB
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 5306:3306
    volumes:
      - "./forrasok/DB/docker_schema_script.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./forrasok/DB/docker_default_data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      network:
        ipv4_address: 192.168.1.101

  api:
    container_name: SecurityApi
    image: axelnemes/securityapi:latest
    ports:
      - 5080:80
      - 5443:443
    networks:
      network:
        ipv4_address: 192.168.1.100

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1